spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.tlavu.educore: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
