spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  error:
    include-message: never
    include-binding-errors: never

logging:
  level:
    com.tlavu.educore: WARN
    org.springframework.security: WARN
    org.springframework.web: ERROR
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    com.zaxxer.hikari: WARN
    com.zaxxer.hikari.HikariConfig: WARN